server {
    listen 80;

    location / {
        # Resolver DNS interno de Google para permitir resolución dinámica en Render
        resolver 8.8.8.8 valid=30s;
        
        # URL completa pública generada por Render
        proxy_pass https://app-5oh8.onrender.com;
        
        proxy_set_header Host app-5oh8.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Permitir conexiones SSL salientes hacia Render
        proxy_ssl_server_name on;
    }
}